/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package mob.programming.nelkinda

import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.shouldBe

class AppTest: FunSpec() {

    init {
        test("123") {
            true shouldBe true
        }
    }
}
